// Synthetic scenarios only. Never automatically loaded into a patient document.
export const documentationDemos = [
    { name: "General Medicine", template: "medicine_opd", text: "Chief complaint: Fever and productive cough.\nHistory: 54-year-old male with fever for three days and productive cough.\nPast history: Known diabetes mellitus and hypertension.\nAssessment: Febrile respiratory illness under evaluation.\nPlan: Clinician requested CBC and chest radiograph." },
    { name: "Surgery", template: "surgery_operative", text: "Pre-op diagnosis: Acute appendicitis.\nPost-op diagnosis: Acute appendicitis.\nProcedure: Laparoscopic appendectomy.\nSurgeon: Dr. Demo Surgeon.\nAnesthesia: General anesthesia.\nFindings: Inflamed appendix.\nTechnique: Appendix removed laparoscopically.\nSpecimens: Appendix sent for histopathology.\nComplications: No intraoperative complications reported.\nDisposition: Recovery room." },
    { name: "Pediatrics", template: "pediatrics_acute", text: "Age: Three years.\nWeight: 12.4 kg.\nChief complaint: Fever and cough.\nHPI: Fever for two days.\nFeeding: Reduced oral intake.\nRespiratory symptoms: Cough.\nAssessment: Acute febrile illness under evaluation.\nPlan: Clinician advised reassessment after investigations." },
    { name: "Obstetrics", template: "ob_prenatal", text: "Gravida: 2.\nPara: 1.\nGestational age: 24 weeks as documented by clinician.\nSymptoms: Routine prenatal review.\nFetal movements: Present by maternal report.\nBP: 112/70 mmHg.\nAssessment: Prenatal review.\nPlan: Clinician advised routine antenatal follow-up." },
    { name: "Gynecology", template: "gyn_opd", text: "Complaint: Heavy menstrual bleeding.\nGynecological history: Symptoms for three cycles.\nMenstrual and reproductive history: Regular cycles with increased bleeding.\nInvestigations: CBC requested.\nImaging: Pelvic ultrasound requested.\nAssessment: Abnormal uterine bleeding under evaluation.\nPlan: Review investigation results." },
    { name: "Radiology", template: "radiology_report", text: "Exam: CT abdomen.\nModality: CT.\nBody region: Abdomen.\nContrast: Intravenous contrast administered.\nClinical indication: Right lower quadrant pain.\nTechnique: Contrast-enhanced axial CT images with reformats.\nFindings: Dilated appendix with surrounding fat stranding.\nImpression: Findings reported as acute appendicitis by the radiologist.\nCritical finding: Acute appendicitis.\nPerson contacted: Referring clinician.\nCommunication method: Telephone." },
    { name: "Oncology", template: "oncology_treatment", text: "Cancer type: Breast carcinoma.\nPrimary site: Left breast.\nStage: Stage II as documented in prior oncology assessment.\nCurrent treatment: Adjuvant systemic therapy.\nTreatment intent: Adjuvant.\nCurrent cycle: Cycle three review.\nSymptoms: Fatigue.\nToxicities: Mild nausea reported.\nTreatment response: Not assessed at this visit.\nPlan: Oncologist requested review of blood counts before confirming the next cycle." },
];
