"use client";

import { ConsentInkField, InkImage } from "./ConsentInkField";
import { SignatureImage, SignaturePad, type Signature } from "./SignaturePad";
import type { Choice, DemoForm, Entry, Field, Language } from "@/lib/demo-consent";

export function DemoConsentPaper({ form, language, onField, onChoice, onSignature, signatureVersion = 0, sections = [0,1,2,3,4,5], saved = false }: {
  form: DemoForm; language: Language; onField?: (key: Field, entry: Entry) => void;
  onChoice?: (key: "data_decision" | "procedure_decision", choice: Choice) => void;
  onSignature?: (key: "patient_signature" | "clinician_signature" | "witness_signature", signature: Signature | null) => void;
  signatureVersion?: number; sections?: number[]; saved?: boolean;
}) {
  const t = form.template[language];
  const field = (key: Field, required = false) => onField ? <ConsentInkField key={key} label={t.labels[key]} value={form.fields[key]} onChange={entry => onField(key,entry)} wording={t} required={required} /> : <div key={key} className="min-w-0 border-b border-slate-200 pb-1"><p className="text-[11px] font-semibold text-slate-500">{t.labels[key]}</p><InkImage label={t.labels[key]} entry={form.fields[key]} /></div>;
  const date = (key: Field) => saved && !form.fields[key]?.text && !form.fields[key]?.ink ? <div><p className="text-[11px] font-semibold text-slate-500">{t.labels[key]}</p><p>{new Date(form.date).toLocaleString(language === "hi" ? "hi-IN" : "en-IN")}</p></div> : field(key);
  const signature = (key: "patient_signature" | "clinician_signature" | "witness_signature") => onSignature ? <SignaturePad key={`${key}-${signatureVersion}`} label={t.labels[key]} hint={t.ink_hint} clearLabel={t.clear} onChange={ink => onSignature(key,ink)} /> : form[key] ? <div><p className="text-[11px] font-semibold text-slate-500">{t.labels[key]}</p><SignatureImage signature={form[key]} label={t.labels[key]} /></div> : <p className="text-xs text-slate-400">{t.labels[key]}: —</p>;
  const choice = (key: "data_decision" | "procedure_decision") => <fieldset className="mt-4 space-y-3 border-l-2 border-teal-700 pl-4"><legend className="sr-only">{key === "data_decision" ? t.sections[1] : t.sections[2]} — {t.choose}</legend>{(["accepted","declined"] as const).map(value => <label key={value} className="flex items-start gap-3 text-sm leading-6"><input type="checkbox" disabled={!onChoice} checked={form[key]===value} onChange={() => onChoice?.(key, form[key]===value ? null : value)} className="mt-1 h-4 w-4 shrink-0 accent-teal-700 disabled:opacity-100" /><span>{key === "data_decision" ? value === "accepted" ? t.data_yes : t.data_no : value === "accepted" ? t.procedure_yes : t.procedure_no}</span></label>)}</fieldset>;
  const heading = (index: number) => <h3 className="mb-4 border-b border-slate-200 pb-2 text-sm font-bold text-teal-900">{index+1}. {t.sections[index]}</h3>;
  return <div lang={language} className="demo-consent-paper space-y-7 text-sm leading-6 text-slate-800">
    <header className="border-b-2 border-teal-800 pb-5"><div className="mb-3 flex items-center justify-between gap-3"><span className="text-[10px] font-bold uppercase tracking-widest text-teal-800">{language === "en" ? "Common form · All departments" : "सभी विभागों के लिए समान पत्र"}</span>{form.template.version === "demo-consent-v1" && <span className="rounded border border-amber-300 px-2 text-[10px] font-bold text-amber-800">DEMO</span>}</div><h2 className="text-xl font-bold tracking-wide text-slate-900">{t.title}</h2><p className="mt-1 text-sm text-slate-500">{t.subtitle}</p><dl className="mt-5 grid gap-x-5 gap-y-2 text-xs sm:grid-cols-2"><div><dt className="inline font-semibold">{t.labels.hospital}: </dt><dd className="inline">{form.hospital_name}</dd></div><div><dt className="inline font-semibold">{t.labels.patient_id}: </dt><dd className="inline">{form.patient_reference}</dd></div><div><dt className="inline font-semibold">{t.labels.date}: </dt><dd className="inline">{new Date(form.date).toLocaleDateString(language === "hi" ? "hi-IN" : "en-IN")}</dd></div></dl></header>
    {sections.includes(0) && <section>{heading(0)}<div className="grid gap-4 sm:grid-cols-2">{field("patient_name",true)}{field("age")}{field("gender")}{field("mobile")}<div className="sm:col-span-2">{field("address")}</div></div></section>}
    {sections.includes(1) && <section>{heading(1)}<p>{t.data_intro}</p><p className="mt-3">{t.data_includes}</p><ul className="my-3 list-disc space-y-1 pl-5">{t.data_items.map(item => <li key={item}>{item}</li>)}</ul><p>{t.data_sharing}</p><p className="mt-3">{t.data_access}</p>{choice("data_decision")}</section>}
    {sections.includes(2) && <section>{heading(2)}<p>{t.procedure_intro}</p><div className="my-4 space-y-4">{field("procedure",true)}{field("purpose",true)}</div><p>{t.questions}</p><p className="mt-3">{t.understand}</p><ul className="my-3 list-disc space-y-1 pl-5">{t.procedure_items.map(item => <li key={item}>{item}</li>)}</ul>{choice("procedure_decision")}</section>}
    {sections.includes(3) && <section>{heading(3)}<p>{t.patient_declaration}</p><div className="mt-4 space-y-4">{field("representative_name",true)}{signature("patient_signature")}{date("patient_date")}</div></section>}
    {sections.includes(4) && <section>{heading(4)}<p>{t.clinician_declaration}</p><div className="mt-4 grid gap-4 sm:grid-cols-2">{field("clinician_name",true)}{field("registration")}<div className="sm:col-span-2">{signature("clinician_signature")}</div>{date("clinician_date")}</div></section>}
    {sections.includes(5) && <section>{heading(5)}{!saved && <p className="mb-3 text-xs text-slate-500">{t.witness_optional}</p>}<div className="space-y-4">{field("witness_name")}{signature("witness_signature")}{date("witness_date")}</div></section>}
    <aside className="border-t border-slate-200 pt-4 text-xs leading-5 text-slate-500"><p className="font-semibold">{t.policy_title || t.demo_title}</p><p className="mt-1">{t.policy_notice || t.demo_notice}</p></aside>
  </div>;
}
